### ISSUE TITLE
Melhorias card #38

### ISSUE THREAD

**Issue by etrajanotw** [Enegrecer/enegrecer-web#113]
Notes:
Este card é resultado de uma série de débitos técnicos identificados durante o desk check do story card #38.

1 - Validações de tamanho de string dos campos:
*"Nome" (não obrigatório) - texto simples com no máximo 40 caracteres;
*"Sobrenome" (não obrigatório) - texto simples com no máximo 40 caracteres,

2 - Validação de senha não é o suficiente (maior que 6 caracteres) 
Hoje a validação da senha só acontece com ela estando vazia ou menor que 6 caracteres. Precisa ser mais elaborada (validar com o negócio se já foi conversada a preocupação da dificuldade da senha).

3 - Exibição dos erros de no cadastro para o usuário (novo layout)
O sistema não informa o que está acontecendo para o usuário. 

4 - Criar uma relação de authentication do banco com cadastro de usuário no banco
No registrar há a opção de preencher nome e sobrenome, mas esses dados são perdidos. Nada é cadastrado na tabela users, apenas um usuário authetication é salvo (login e senha apenas)

**Comment by marianeferroni** [comment]
Card contemplado na funcionalidade de "Cadastrar Denuncia" do Hackathon
