### ISSUE TITLE
Ver estatísticas

### ISSUE THREAD

**Issue by marianeferroni** [Enegrecer/enegrecer-web#160]
Como pessoa do público geral
Quero visualizar as estatísticas sobre racismo e injúria racial no site do verdade seja dita
Para que eu possa ter uma visão real dos casos que acontecem no Brasil.   

Obs: Os dados que entram para a estatística são as denúncias originadas do próprio site "Verdade Seja Dita", que já foram classificadas pelo coletivo e que já foram aceitas. 

**Critérios de Aceitação**
*AC1 - Visualizar total de casos de Racismo*
Dado que eu estou no portal do Verdade Seja Dita
Quando acessar a página principal
Então a quantidade total de casos de Racismo denunciada no site "Verdade Seja Dita" deve ser exibida. 

*AC2 - Visualizar total de casos de Injúria Racial*
Dado que eu estou no portal do Verdade Seja Dita
Quando acessar a página principal
Então a quantidade total de casos de injúria racial denunciada no site "Verdade Seja Dita" deve ser exibida. 

*AC3 - Visualizar total denúncias onde a vítima seja mulher*
Dado que eu estou no portal do Verdade Seja Dita
Quando acessar a página principal
Então porcentagem de casos denunciados no site "Verdade Seja Dita" onde a vítima seja mulher deve ser exibida. 

*AC4 - Visualizar total de denúncias*
Dado que eu estou no portal do Verdade Seja Dita
Quando acessar a página principal
Então a quantidade total de denuncias no site "Verdade Seja Dita" deve ser exibida. 

*AC5 - Visualizar total denúncias onde a vítima tenha até 29 anos*
Dado que eu estou no portal do Verdade Seja Dita
Quando acessar a página principal
Então porcentagem de casos denunciados no site "Verdade Seja Dita" onde a vítima tenha até 29 anos deve ser exibida. 

**Referência de Layout**
Tela Home https://zpl.io/Vq65vQZ

**Comment by Lorena** [comment]
Estou com problema no AC3 pq informar o gênero não é uma informação obrigatória. Da mesma forma no AC5. Não é obrigatório informar a idade. =( 
O que podemos fazer?

**Comment by marianeferroni** [comment]
Oi Lores, 

Não sei pq isso seria um problema. 
Podemos apresentar a estatística de apenas os registros que preencheram. 

Para AC3 e AC5 a estatística é mostrada com os dados que temos em mãos.

**Comment by Lorena** [comment]
No meu ponto de vista é um problema, pq por exemplo, a estatística que olha a idade está dando 0 (Zero) casos. Mas creio que vale uma reflexão nesses pontos.
