### ISSUE TITLE
Ver Próximos Passos

### ISSUE THREAD

**Issue by marianeferroni** [Enegrecer/enegrecer-web#161]
Como testemunha
Quero visualizar as informações do que posso fazer depois da denúncia
Para que eu possa acompanhar saber onde procurar ajuda junto ao coletivo Enegrecer  e saber dos meus diretos e auxiliar a vítima de racismo/ injúria racial

**Critérios de Aceitação**
*AC1 - Visualizar informação sobre os próximos passos*
Dado que eu estou no portal do Verdade Seja Dita
Quando acessar a página “E depois da Denúncia?”
Então o conteúdo sobre os próximos passos depois da denúncia deve ser apresentado.  

*AC2 - Visualizar informação sobre os próximos passos - fluxo de denúncia*
Dado que eu estou no portal do Verdade Seja Dita
Quando eu concluir minha denúncia
Então o conteúdo sobre os próximos passos depois da denúncia deve ser apresentado. 

**Referência de Layout**
Tela "E depois da denúncia" https://zpl.io/b6lwqgP

**Comment by llevvi** [comment]
Comecei a trabalhar nesse issue/card :)

**Comment by llevvi** [comment]
Vou deixar o card por enquanto, visto que não é uma prioridade e ainda não temos o texto que vai ser enviado pelo Coletivo.

**Comment by marianeferroni** [comment]
Pendente: Conteúdo a ser enviado pelo Coletivo Enegrecer
