### ISSUE TITLE
Fotos dos colaboradores na página "Sobre"

### ISSUE THREAD

**Issue by marianeferroni** [Enegrecer/enegrecer-web#168]

**Comment by llevvi** [comment]
Vou trabalhar nesse card. No entanto, ainda não consigo mover os cards entre as lanes.

**Comment by marianeferroni** [comment]
Estou movendo para vc @llevvi :)

**Comment by marianeferroni** [comment]
Egileu Trajano

**Comment by llevvi** [comment]
@marianeferroni as inclui no ambiente de desevolvimento :)
