### ISSUE TITLE
Transformar o segundo botão "Denunciar" em um link todo clicável

### ISSUE THREAD

**Issue by Lorena** [Enegrecer/enegrecer-web#238]
Hoje somente o texto do segundo botão "Denunciar" que está clicável.

Por isso, é importante transformar o segundo botão "Denunciar" da home em um link todo clicável, e não somente a descrição "Denunciar".

**Tasklist**
- [ ]

**Comment by erikatech** [comment]
https://github.com/Enegrecer/enegrecer-web/pull/250

**Comment by erikatech** [comment]
Merged w/ dev
