### ISSUE TITLE
Menu lateral da denúncia não está acompanhando o formulário

### ISSUE THREAD

**Issue by marianeferroni** [Enegrecer/enegrecer-web#243]
Ao abrir o formulário de Cadastro de Denúncias e ir navegando para as sessões do formulário (Dados do denunciante, Dados da vítima, Informações Legais, Dados do 
agressor e Descrição da agressão), o menu não acompanha o restante do formulário. 

Ao clicar em alguma sessão do menu lateral, ele não está redirecionando a sessão correspondente. 

Ao navegar em alguma sessão do formulário, o menu lateral não está ficando em negrito na sessão correspondente.

![Screen Shot 2018-04-25 at 17.41.15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c2bb5ad7084c0013c983ac/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f66b7191a379e80c2f50415e4bbe5d4a1f06a3a3dc78e2a436628f555aead0645a72c03e10acea811fbf03ec218c4cd3b4b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca5cf043e84c57a3133065f43b.png)

**Comment by erikatech** [comment]
Preciso conversar com  @btomaz pra saber qual vai ser o comportamento ideal dessa interação.
