### ISSUE TITLE
Campo "Genero" está duplicado nos dados do Denunciante

### ISSUE THREAD

**Issue by marianeferroni** [Enegrecer/enegrecer-web#244]
No Cadastro da denúncia, o campo gênero apresenta de forma duplicada.
![Screen Shot 2018-04-25 at 17.46.55.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c2bb5ad7084c0013c983ac/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f66b7191a379e80c2f57415a4bbe5d4a1f06a3a3dc78e2a436628f555aead0645a72c03e10acea811fbf03ec218c4cd3b4b99850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca5cf043e84e50a213306bf43b.png)

**Comment by erikatech** [comment]
Merged w/ dev.
