### ISSUE TITLE
"Marque se você é a vítima" não está funcionando

### ISSUE THREAD

**Issue by marianeferroni** [Enegrecer/enegrecer-web#245]
No cadastro de Denúncia, ao clicar na opção "Marque se você é a vítima", o comportamento seria copiar as mesmas informações dos dados do denunciante para os dados da vítima, atualmente isso não está ocorrendo.
![Screen Shot 2018-04-25 at 17.50.58.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c2bb5ad7084c0013c983ac/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f66b7191a379e80c2e51415a46be5d4a1f06a3a3dc78e2a436628f555aead0645a72c03e10acea811fbf03ec218c4cd3b4b99850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca5cf043e8485ca71b366af43b.png)

**Comment by erikatech** [comment]
https://github.com/Enegrecer/enegrecer-web/pull/258
