### ISSUE TITLE
Remover campo "Bairro" dos dados do denunciante

### ISSUE THREAD

**Issue by marianeferroni** [Enegrecer/enegrecer-web#246]
No cadastro de Denúncia, remover campo "Bairro"na descrição do denunciante, que não faz parte do escopo.
![Screen Shot 2018-04-25 at 18.04.29.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c2bb5ad7084c0013c983ac/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f66b7191a379e70c2b55415d47be5d4a1f06a3a3dc78e2a436628f555aead0645a72c03e10acea811fbf03ec218c4cd3b4b99850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca5cf042e1495da3143465f43b.png)

**Comment by erikatech** [comment]
No caso, seria no form de descrição do agressor, certo?

**Comment by erikatech** [comment]
Merged with dev.
