### ISSUE TITLE
Precisamos rever a regra 'import/extensions' do code climate

### ISSUE THREAD

**Issue by hsbrighenti** [Enegrecer/enegrecer-web#29]
Regra é responsável por mais de 40 erros no code climate com a descrição:

"Missing file extension for [...]" 

reclamando de imports no javascript que referenciam modulos do node, para os quais não existe extensão mesmo.

**Comment by hsbrighenti** [comment]
O Code Climate oferece opção de utilizar nosso próprio arquivo de configuração: 

https://docs.codeclimate.com/docs/eslint#section-configure-the-engine

talvez isso normalize o eslint

**Comment by paulogama** [comment]
O @BrunoQuaresma e eu estávamos analisando, pois, em teoria as nossas configurações foram alteradas. No nosso arquivo _eslintrc.json_ modificamos o `extends para 'airbnb'` que seria a mesma leitura que o _lint_ está fazendo e os nossos editores de texto também. Vou analisar novamente para tentar descobrir o problema.

Obrigado @hsbrighenti :)

**Comment by BrunoQuaresma** [comment]
@hsbrighenti acho que se tu der um rebase da tua branch com a master os problemas devem desaparecer.

**Comment by hsbrighenti** [comment]
@paulogama @BrunoQuaresma 

Local está tudo certo, e funcionando bem. O problema me parece ser que o code climate não está usando exatamente as mesmas regras. 

Não sei se isso teria a ver com as modificações que vcs fizeram para utilizarmos o linter no moldes Airbnb, acho que isso ficou certinho :)

Quanto à questão de branches eu não estou usando nenhuma. Basta clicar no badge do code climate no Readme da master mesmo e ir em issues que da pra ver os issues que eu estou falando lá. 

Aqui tem um link direto tb : https://codeclimate.com/github/Enegrecer/enegrecer-web/issues

**Comment by BrunoQuaresma** [comment]
Ahhh saquei. Vlws @hsbrighenti
