### ISSUE TITLE
Criar Denúncia

### ISSUE THREAD

**Issue by noliveir** [Enegrecer/enegrecer-web#30]
Para registrar um relato de uma denúncia
Como um denunciante
Gostaria de conseguir registrar os detalhes do fato ocorrido

Campos
- Categoria: obrigatório; combo [Injúria Racial e Racismo]
- Detalhamento: obrigatório; texto com múltiplas linhas;
- Data e hora do ocorrido: obrigatório; datetime picker

Critérios de Aceite
AC01 - Formulário
Dado um usuário logado na tela principal
Quando clico em "Denuncie aqui"
Então vejo um formulário com a categoria, o detalhamento, data e hora do ocorrido

AC02 - Status
Dado que usuário preencheu todos campos obrigatórios
Quando clico em "Salvar"
Então a denúncia é salva com o status "Nova"

AC03 - Data e Hora atual
Dado que usuário preencheu todos campos obrigatórios
Quando clico em "Salvar"
Então a denúncia é salva com a data e hora atual

AC04 - Denunciante
Dado que usuário preencheu todos campos obrigatórios
Quando clico em "Salvar"
Então a denúncia é salva com o usuário logado registrado como o denunciante

**Comment by hsbrighenti** [comment]
O PR #44 foi mergeado e fechado. Acredito que isso resolve esse card, correto @paulasf @guilhermecorsino ?

**Comment by guilhermecorsino** [comment]
Isso, com esse merge esse caso está resolvido. Muito obrigado @hsbrighenti :) 👍
