### ISSUE TITLE
Página inicial do Enegrecer

### ISSUE THREAD

**Issue by noliveir** [Enegrecer/enegrecer-web#32]
<img width="1024" alt="screen_shot_2017-08-31_at_4 10 42_pm" src="https://user-images.githubusercontent.com/30049771/29983017-56d6c808-8f2a-11e7-851a-f59aa47b0784.png">

<img width="1029" alt="screen_shot_2017-08-29_at_4 31 24_pm" src="https://user-images.githubusercontent.com/30049771/29983001-48f6e5c4-8f2a-11e7-9784-dde86f898c3c.png">
Eu, Joana Informada,
quero poder ver a página Enegrecer e usar a opção para denunciar racismo,
pois procuro uma alternativa para tornar público o racismo que sofri.

Notas:

Pensamos em exibir a tela inicial com o botão vermelho escrito "Denunciar Racismo", como na imagem em anexo. O botão redireciona para outra página, ainda não definida nesta estória.

Também serão exibidas informações básicas (textos definitivos ainda não informados), e no rodapé (imagem em anexo) os links de redes sociais.
Layout no Zeplin.

--------------------------------------------------------------------------------

**Critérios de Aceite**

*AC01 * 
**Dado que** eu entrei na tela inicial do Verdade Seja Dita, 
**quando** visualizar a tela que foi exibida 
**então** verei a opção para "denunciar racismo"

*AC02* 
**Dado que** visualizei a opção para denunciar  
**quando** escolher a opção para "Denunciar racismo"
**então** sairei da tela inicial

*AC03*

**Dado que** eu entrei na tela inicial do Verdade Seja Dita,  
**quando** visualizar a tela que foi exibida 
**então** verei o texto explicativo da página.

*AC04*

**Dado que** eu entrei na tela inicial do Verdade Seja Dita,  
**quando** visualizar a tela que foi exibida 
**então** verei a opção de "Entrar/registrar" para me autenticar na página.

*AC06*

**Dado que** eu entrei na tela inicial do Verdade Seja Dita ,  
**quando** visualizar a tela que foi exibida 
**então** verei a imagem de fundo da página.

*AC07*

**Dado que** eu entrei na tela inicial do Verdade Seja Dita,  
**quando** visualizar a tela que foi exibida 
**então** verei o título da página Verdade Seja Dita.

*AC08*

**Dado que** eu entrei na tela inicial do Verdade Seja Dita,
**quando** visualizar a tela que foi exibida, 
**então** no fim da página, verei o rodapé com a informação "Siga-nos",  contendo os ícones para redes sociais do Enegrecer (Facebook, Twitter e Instagram).

**Comment by BrunoQuaresma** [comment]
Antes de mexer nela terminei fazendo algumas refatorações pra ficar melhor de implementar. Pull-request: #35

**Comment by CarolTozzi** [comment]
AC3 e AC8 estão faltando, precisamos que o coletivo mande o texto e os links das redes sociais.
AC7 atualizado para "Verdade seja dita".
