### ISSUE TITLE
Organizar documentação do projeto

### ISSUE THREAD

**Issue by noliveir** [Enegrecer/enegrecer-web#33]

**Comment by hsbrighenti** [comment]
Tasklist:

- [ ] Revisar README
- [ ] Explicar estrutura de pastas e códigos fonte do projeto
- [ ] Estratégia de qualidade
- [ ] Explicar a utilização do Redux-Saga

**Comment by roMendes** [comment]
Ver se alguém atualmente no projeto pode assumir as atividades restantes, uma vez que Henrique saiu do projeto e a maioria do que falta é mais dev...
Sobre o último item da tasklist, alguém v necessidade de informações criptografadas no Git????

**Comment by roselmamendes** [comment]
olá posso ajudar nessa? @roMendes

**Comment by hsbrighenti** [comment]
@roMendes A idéia de informações criptografadas era para guardarmos informações do tipo login de administrador do firebase, futuramente credenciais de qualquer outro serviço pago que formos usar (um futuro host se trocarmos, um servidor de emails, sei lá...)

Isso surgiu por que algumas vezes já nos perdermos sobre onde estavam essas credenciais do firebase e fomos achar num card no "lixo" do trello para resgatá-las. Precisamos de um lugar para guardá-las, e como estamos usando apenas coisas abertas (github, gitter, etc.) não podemos escrever elas diretamente para que qualquer um acesse, estes são serviços pagos. 

Porém isso está funcionando no boca a boca hoje em dia... E outras soluções podem ser pensadas também.
