### ISSUE TITLE
Informações da Vítima que não é denunciante

### ISSUE THREAD

**Issue by noliveir** [Enegrecer/enegrecer-web#37]
**Eu**, Joana Informada,
**desejo** inserir as informações de uma pessoa vítima,
**para** registrar uma denúncia de racismo/injúria racial.  

*Notas*

1. O padrão é a pessoa denunciante não ser a vítima. 
2. Conheço a vítima? - O valor desta pergunta está em saber apenas se a pessoa denunciante tem qualquer tipo de relação com a pessoa vítima, não restringe preenchimento de campos.
3. Se o crime for racismo, então não tem uma vítima específica.
4. Concordamos que a submissão das informações será feita em etapas.

**Critérios de Sucesso**

* **AC01 - Informações sobre a pessoa vítima**
**Dado que** estou preenchendo as informações para fazer uma denúncia,
**Quando** vejo na tela a parte em que devo informar e identificar quem é a vítima,
**Então** preencho as informações sobre a vítima:
"Conheço a vítima?" (**Deselecionado por padrão**) - [sim ou não],
*"Cor ou Raça" (não obrigatório) - opções para seleção [preta, parda, indígena],
*"Nome" (não obrigatório) - texto simples com no máximo 40 caracteres 
*"Gênero" (não obrigatório) -  É uma caixa de texto simples de 15 caracteres, opções de sugestão placeholder [Feminino, Masculino, Não-Binário, Agênero, etc..]
*"Data de Nascimento"  *(não obrigatório), somente datas válidas após 1900, menor que a data atual. 
*"Endereço" - texto simples com no máximo 255 caracteres  (não obrigatório),
*"Naturalidade" texto simples com no máximo 40 caracteres  (não obrigatório),
*"Telefone" formato 10 a 11 dígitos (não obrigatório)
*"email" formato válido (não obrigatório)
*"Por favor, descreva aqui as características da vítima." (obrigatório), texto com múltiplas linhas ( sugestão de 255 caracters).

* **AC02 - Denunciante não sabe informações "oficiais"(nome, nascimento, etc.) da vítima**
**Dado** que inseri nenhuma informação da pessoa vítima,
**Quando** seleciono a opção para "Concluir denúncia",
**Então** sou  alertada que "Você não inseriu informações sobre a vítima. Precisamos que você complemente inserindo ao menos uma descrição informal sobre a pessoa." com a opção para fechar a mensagem, e a denúncia não é registrada sem informações de vítima.

* **AC03  - Descrição de características da pessoa vítima**
**Dado**  que estou inserindo informações sobre uma pessoa vítima,
**Quando** vejo o espaço para descrição de características
**Então** vejo uma sugestão de como preencher o espaço, existe um texto escrito: "Era uma mulher negra, com aproximadamente 40 anos, magra, alta com cabelo curto...",  e quando seleciono  para inserir a informação o texto de sugestão some.

**Comment by izaeleffemberg** [comment]
-> Modificar "Sou a vítima" para "conheço a vítima";

**Comment by izaeleffemberg** [comment]
Certificar que as informações sobre uma vítima que não é denúnciante estão sendo salvas.

**Comment by morrico** [comment]
Em outro card, o componente de mensagem irá exibir os nomes dos campos que estão faltando, assim como tentar fazer com que a pessoas preencha os campos desejados de informações.

**Comment by morrico** [comment]
Conversamos e o Critério AC02 foi modificado. Na versão anterior seria possível concluir uma denúncia sem informações da vítima, agora a pessoa precisa pelo menos inserir uma descrição se ela Não tem dados oficiais sobre a vítima, um exemplo seria "a vítima foi uma mulher negra, alta, com cerca de 30 anos, usava vestido e bolsa, etc...
