### ISSUE TITLE
Registrar Testemunhas

### ISSUE THREAD

**Issue by noliveir** [Enegrecer/enegrecer-web#38]
**Eu**, Joana Informada,
**desejo** informar sobre uma pessoa que foi TESTEMUNHA,
**para** registrar uma denúncia de racismo.  

Notas:

- Buscar código do card 37, pois será uma replicação deste card com poucas mudanças.

- Nas mensagens, o que pensamos foi:
  - A. Se a mensagem só traz sugestão de preenchimento de campos NÃO obrigatórios, Joana consegue concluir a denúncia selecionando a opção disponível
para avançar (por exemplo, OK)
 -  B. Se a mensagem traz solicitação de preenchimento de campos NÃO obrigatórios, e também de campos obrigatórios, Joana não consegue concluir a denúncia.

- Não é obrigatório inserir testemunhas, mas devemos influenciar a pessoa denunciante a incluir algum detalhe. Ao tentar concluir a denúncia sem testemunhas a pessoa será questionada se quer mesmo concluir sem as informações da testemunha, porém ela tem a opção de concluir sem testemunhas.

Pare esta primeira Onda será possível inserir apenas UMA pessoa testemunha.

---------------
**Critérios de Sucesso**

* **AC01 - Sei as informações sobre a pessoa testemunha**
**Dado que** sei informações sobre uma testemunha da situação que estou denunciando,
**Quando** vejo na tela a parte em que devo incluir informações sobre a pessoa que foi testemunha,
**Então** preencho as informações sobre a testemunha:
*"Nome" *(não obrigatório)* - texto simples com no máximo 40 caracteres,
*"Cor ou Raça" (não obrigatório) - opções para seleção [preta, parda, branca, indígena, amarela],
*"Gênero" (não obrigatório) -  É uma caixa de texto simples de 15 caracteres, opções de sugestão placeholder fonte de cor clara [Feminino, Masculino, Não-Binário, Agênero...]
*"Data de Nascimento"  *(não obrigatório)*, somente datas válidas após 1900, menor que a data atual. 
*"Telefone" (não obrigatório),
*"Por favor, descreva aqui  características da testemunha." (não obrigatório), texto com múltiplas linhas ( sugestão de 255 caracters), e placeholder fonte de cor clara ["Era uma mulher branca, estava próxima de mim, tinha com cabelo preto e curto, com camisa de uma escola..."]

* **AC02 - Denúncia concluída sem pessoa testemunha**
**Dado que** não sei as informações da pessoa testemunha,
**Quando** já preenchi todas as outras informações necessárias para uma denúncia e seleciono a opção para "Concluir denúncia",
**Então** sou informada que "Você não nos deu informações sobre uma testemunha. A denúncia terá maior valor com esses dados. Você pode cancelar e inserir essas informações. ",  e posso escolher a opção "OK" ou "Cancelar.".

* **AC03 - Completar denúncia com informações da pessoa testemunha**
**Dado que** tinha selecionado a opção "Concluir Denúncia", mas desejo completar a denúncia com informações da pessoas testemunha,
**Quando** seleciono a opção para voltar para inserir mais informações,
**Então** continuo vendo o formulário onde devo inserir as informações de uma pessoa que foi testemunha e posso incluir essas informações.

**Comment by karlafalcao** [comment]
Desk Check 1

AC01
** Falta colocar limite de caracteres am todos os campos de texto
* Nome: Falta colocar limite de caracteres
* Gênero: Placeholder
* Data Nascimento: Validação do formato
**Adicionar dados da testemunha no banco

AC02 - ok

AC03
Criar Sugestão de preenchimento de campos 
Colocar junto com o popup de sugestão de vitima

**Comment by lucianavmco** [comment]
Raça da testemunha não pode ser resumida a negra e parda. Adicionar todas as raças consideradas pelo ibge.

**Comment by marianeferroni** [comment]
Card contemplado na funcionalidade de "Cadastrar Denuncia" do Hackathon
