### ISSUE TITLE
Registrar Agressores

### ISSUE THREAD

**Issue by noliveir** [Enegrecer/enegrecer-web#39]
**Eu**, Joana Informada, 
**desejo** informar quem é a pessoa agressora, 
**para** registrar uma denúncia de racismo.

**BLOQUEADO** - Aguardando conclusão do card 37, pois será uma replicação deste card com poucas mudanças

---------------
**Critérios de Sucesso**

**AC01 - Informar pessoa agressora identificada em uma denúncia**
**Dado que** eu estou informando uma denúncia
**E** tenho a informação de pessoa agressora para reportar
**E** eu possuo o nome da pessoa agressora
**Quando** eu selecionar a opção de inserir uma pessoa agressora
**E** selecionar a opção “Pessoa agressora identificada”.
**Então** eu preencho as informações da pessoa agressora
*"Nome"* (obrigatório) - texto simples com no máximo 40 caracteres
*"Gênero"*  (obrigatório) - opções para seleção [Feminino, Masculino, Não-Binário, Agênero] 
*"Cor ou Raça"* (obrigatório) - opções para seleção [branca, preta, amarela, parda ou indígena] 
*"Data de Nascimento"* (não obrigatório), somente datas válidas após 1900, menor que a data atual. 
*”Residência"* (não obrigatório),
*"Estado" (obrigatório),
*"Telefone" (não obrigatório) 
*"email"* (não obrigatório) 
*”Mais Informações”* (não obrigatório), texto com múltiplas linhas.

**AC02 - Inserir pessoa agressora não identificada em uma denúncia**
**Dado que** eu estou informando uma denúncia
**E** tenho a informação de pessoa agressora para reportar
**E** eu possuo o nome da pessoa agressora
**Quando** eu selecionar a opção de inserir uma pessoa agressora
**E** não selecionar a opção “Pessoa agressora identificada”
**Então**  eu preencho as informações da pessoa agressora
*"Nome"* (não obrigatório) - texto simples com no máximo 40 caracteres 
*"Gênero"* (não obrigatório) - opções para seleção [Feminino, Masculino, Não-Binário, Agênero] 
*"Cor ou Raça"* (não obrigatório) - opções para seleção [branca, preta, amarela, parda ou indígena] 
*"Data de Nascimento"* (não obrigatório), somente datas válidas após 1900, menor que a data atual. 
*"Residência"* (não obrigatório), local picker *"Telefone" (não obrigatório) *"email" (não obrigatório) 
*"Mais Informações”* (obrigatório), texto com múltiplas linhas.

**AC03 - Concluir denúncia  sem informar os dados obrigatórios**
**Dado que** eu preenchi as informações da pessoa agressora
**E** eu não preenchi as informações obrigatórias
**Quando** escolher a opção “Concluir Denúncia“
**Então** a mensagem de erro “Os campos obrigatórios não foram preenchidos” é apresentada
**E** os campos não preenchidos serão destacados em vermelho
**E** a denúncia não será registrada

**AC04 - Concluir denúncia**
**Dado que** eu preenchi as informações da pessoa agressora
**E** eu preenchi as informações obrigatórias
**Quando** escolher a opção “Concluir Denúncia“
**Então** a denúncia será registrada

**Comment by marianeferroni** [comment]
Dúvidas: 

AC01
"Agressor foi identificado?" (obrigatório) - selecionar esta opção. 
Essa opção é um radio de sim/não? E se a Joana selecionar a opção "Não" ? 

- Para denunciar é obrigatório que a vítima ou testemunha saiba o Nome do agressor? Não é possível abrir uma denúncia onde a pessoa possa descrever o agressor sem informar o nome dele?

**Comment by marianeferroni** [comment]
Posso ter mais de um agressor para uma mesma denúncia? 
Posso alterar / excluir o agressor cadastrado na denúncia?

**Comment by morrico** [comment]
@marianeferroni - sobre ser "radio", estamos usando Specification by Example, e a ideia central é que este detalhe de implementação seja decidido pelo time de pessoas desenvolvedoras junto com UX para não sermos tão específicas a ponto de limitar a ideação de soluções que sejam simples e eficazes, ou mesmo limitar por plataforma. Participar dessa construção é positivo, mas tomar essa decisão sozinha pode não ser a melhor opção para o produto.

**Comment by morrico** [comment]
@marianeferroni - Sobre "Posso ter mais de um agressor para uma mesma denúncia?
Posso alterar / excluir o agressor cadastrado na denúncia?"
Nesta primeira onde teremos apenas 1 agressor. Decidimos descartar a inclusão de vários agressores nesta primeira onda, para conseguirmos avançar e pegar feedback com o pessoal do Enegrecer da denúncia como um todo, sem muitos detalhes. Incluiremos mais estórias nas próximas ondas, e aí incluiremos mais agressores, vítimas, etc.

**Comment by thenuts** [comment]
@morrico  Acho que a principal dúvida e eu não sei responder é que não é conflintante o Nome ser obrigatório se existe a opção "Agressor foi identificado?"  ?
Outra dúvida que eu também tenho é se deve ter a opção de editar e excluir.

**Comment by morrico** [comment]
@thnuts Sim, está mesmo em aberto e gerando dificuldade para interpretação. Parece conflitante se o que vc entende por identificado significar exatamente "sei os dados pessoais do agressor".

Perguntei ao Jonathan e o que ele respondeu foi que estão debatendo. Então podemos fazer o seguinte, seguir pelo ciclo Build - Measure - Learn. A gente permite criar a denúncia sem o nome, sem criar limitações, e pegamos feedback. As vezes é mais fácil para o cliente tomar decisão usando o produto. 

É mais prioritário para o Enegrecer saber que a situação de racismo ocorreu, ou saber quem foi o agressor? A resposta que ainda não temos é talvez no sentido de entender se mesmo não sabendo o nome do agressor, mas sabendo que a pessoa foi identificada (não necessariamente pela denunciante), se ainda assim a denúncia gera valor para os objetivos do Enegrecer.

Se pensarmos em uma situação em que Joana Informada viu alguém sofrer racismo, e ela viu que foi um homem, branco, cabelos pretos, camisa amarela, mas ela Não sabe o nome dele, a denúncia tem utilidade? Não sabemos, vamos experimentar sem limitações e ver o que acontece?

**Comment by morrico** [comment]
@thenuts Nesta primeira teremos apenas 1 agressor, não teremos algo como adicionar agressor, então se a pessoa denunciante quiser  "excluir" é só apagar os dados que ela informou.

**Comment by marianeferroni** [comment]
Funcionalidade contemplada no card "Cadastrar Denúncia" do Hackathon
