### ISSUE TITLE
E-mail permitido para denunciar

### ISSUE THREAD

**Issue by morrico** [Enegrecer/enegrecer-web#40]
**Card revisado por: Izael, Luciana, Juba e Priscila - 02/01/18**
**Card revisado por: Marcella, Luciana, Juba e Priscila - 27/02/18**

Validação de E-mail

**EU**, Joana Informada,
**PRECISO** ter um email válido,
**PARA** registrar uma denúncia.

Notas:
A pessoa preenche os dados da denúncia. Após inserir o e-mail a pessoa deve realizar a ação de enviar, e então a página atualiza explicando que falta apenas a validação para fazer a denúncia.
 Esta ordem de ações é necessária para previnir  o abandono (não validação do e-mail) da denúncia pq o fluxo de autenticação será quebrado .

A validação do email da pessoa só deve ocorrer apenas uma vez para o mesmo email.

--------------------------------------------------------------------------------

**Critérios de Sucesso**

**AC01** 
**Dado que** necessito fazer uma denúncia, 
**quando** insiro dados da denúncia e meu email.
**então** ao finalizar, espero que uma mensagem de validação chegue no meu email.

**AC02**
**Dado que** recebi um email de validação,
**quando** realizo a validação,
**então** tenho a confirmação de que minha denuncia foi registrada.

**AC03**
**Dado que** recebi um email de validação,
**quando** não realizo a validação,
**então** não tenho a confirmação de que minha denúncia foi registrada.

**Comment by marianeferroni** [comment]
Lembrete: Verificar com o coletivo qual é a melhor forma de identificar a pessoa que está denunciado, se faz sentido criar uma validação do e-mail e quais serão essas validações.

**Comment by marianeferroni** [comment]
Escopo contemplado no card de "Cadastrar Denúncia" do hackathon
