### ISSUE TITLE
Verificar se todas as estórias condizem com os termos do domínio

### ISSUE THREAD

**Issue by camilalabes** [Enegrecer/enegrecer-web#49]

**Comment by camilalabes** [comment]
Aparentemente, o nome "autor" tem ambiguidade entre: autor da denuncia e autor da "agressão". 

Sugestões: denunciado, acusado.

Vou verificar com o resto do time. ;)

**Comment by hsbrighenti** [comment]
+1 Agressor

**Comment by guilhermecorsino** [comment]
+1 Agressor
