### ISSUE TITLE
Informações da Vítima que é a Denunciante

### ISSUE THREAD

**Issue by morrico** [Enegrecer/enegrecer-web#74]
CARD INCOMPLETO

**Eu**, Joana Informada,
**desejo** fazer uma denúncia,
**porque** fui vítima de racismo/injúria racial.  

*Notas*

BLOQUEADO - Aguardando conclusão do card 75, pois algumas informações serão preenchidas a partir das informações que foram inseridas na pessoa denunciante.

1. O padrão é a pessoa denunciante não ser a vítima, ela precisa escolher a opção que informa que ela é a vítima.
2. Conheço a vítima? - O valor desta pergunta está em saber apenas se a pessoa denunciante tem qualquer tipo de relação com a pessoa vítima, não restringe preenchimento de campos.
3. Se o crime for racismo, então não tem uma vítima específica, porém, ainda assim, a pessoa pode dizer que é a vítima, pois as denúncias serão analisadas manualmente.
4. Existe dependência das informações de cadastro da pessoa que fez login.

**Critérios de Sucesso**

* **AC01 - Informações sobre a pessoa vítima**
**Dado que** estou preenchendo as informações para fazer uma denúncia,
**Quando** vejo na tela a parte em que devo informar e identificar quem é a vítima,
**Então** informo que "Sou a vítima." (**obrigatório**), e então minhas informações são exibidas nos campos onde aparecem as informações de pessoa denunciante.

**Comment by Prilu** [comment]
Este card não será mais necessário. O escopo está coberto no card 75.
