### ISSUE TITLE
Melhorias Card 37

### ISSUE THREAD

**Issue by morrico** [Enegrecer/enegrecer-web#77]
**Pareando Juba e Mila**

- Remover a opção indígena de raça da vítima
- Não permitir números e acentos no campo nome
- Placeholder na cor cinza clara
- Inserir texto explicativo para o campo informando qual a qtd limite de caracters (No máximo XY caracters)
- Texto da descrição fica estranho quando a pessoa denunciante digitou todas as informações menos a única obrigatória que é a descrição.
- Clicar e sumir o texto no placeholder.
- Solucionar erro  na máscara da data de nascimento do formulário Informações da vítima.
![erro card37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a989db62120d0011bd93f4/125516c66e82c728ace21e0d46ed86882cc280a89dedec14e611b2843b492d762a10e17132d0ba29e813225459594dad410a5c44fcfbdf2aa1b56a728f4e17ff933c0120996048e6edc00db513bb29814e80b7be8c4bc6ea3f2de582895d73.png)

**Comment by izaeleffemberg** [comment]
- Remover a opção indígena de raça da vítima OK
- Não permitir números e acentos no campo nome OK
- Placeholder na cor cinza clara OK
- Inserir texto explicativo para o campo informando qual a qtd limite de caracters (No máximo XY caracters)
- Texto da descrição fica estranho quando a pessoa denunciante digitou todas as informações menos a única obrigatória que é a descrição. OK
- Clicar e sumir o texto no placeholder.
- Solucionar erro na máscara da data de nascimento do formulário Informações da vítima.

**Comment by izaeleffemberg** [comment]
Obs: validação do número do telefone tá com problema.

**Comment by izaeleffemberg** [comment]
Desk Check 04/01/18:

Remover a opção indígena de raça da vítima (Aprovado)
Não permitir números e acentos no campo nome **(colocar a mascara no campo nome para que não aceite acento e informar que não permitdo acentos, numeros e caracteres epeciais)**
Placeholder na cor cinza clara **(Aprovado)**
Inserir texto explicativo para o campo informando qual a qtd limite de caracters (No máximo XY caracters) **(Aprovado)**
Texto da descrição fica estranho quando a pessoa denunciante digitou todas as informações menos a única obrigatória que é a descrição. **(Aprovado)**
Clicar e sumir o texto no placeholder. **(Não aprovado)**
Solucionar erro na máscara da data de nascimento do formulário Informações da vítima. **(Aprovado)**

**Comment by Prilu** [comment]
Revisão de valor de negócio 12/01/18:

Não permitir números e acentos no campo nome (colocar a máscara no campo nome para que não aceite acentos e informar que não é permitido acentos, números e caracteres especiais) 

- Foi discutido que este AC é irrelevante para o momento do projeto. Entendemos que não há problemas técnicos que impedem a acentuação e fica mais amigável para o usuário. 

Clicar e sumir o texto no placeholder. (Não aprovado)

-  Este item será atendido após nova versão da UI e estrutura de componentes.
